services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    expose:
      - '4000'
    ports:
      - '4000:4000'
    depends_on:
      auth-service-postgres:
        condition: service_healthy
    links:
      - auth-service-postgres
  auth-service-postgres:
    container_name: auth-service-postgres
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    expose:
      - '5432'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: example
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
